Repository juftin/camply, pull requests merged in 2022-09, with the labels that each got.

#123 BugFix: No Equipment to Iterate On
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  camply/notifications/base_notifications.py
  docs/examples/example_search.yaml
  pyproject.toml
  tests/command_line_test.sh
  tests/yaml/example_campsite_search.yaml
  tests/yaml/example_search.yaml
Labels: bug, BUMP_PATCH

#125 Update documentation on how to specify multiple notification providers
  README.md
Labels: documentation, BUMP_PATCH

#126 Add ability to notify via Twilio SMS
  camply/cli.py
  camply/config/__init__.py
  camply/config/file_config.py
  camply/config/notification_config.py
  camply/notifications/__init__.py
  camply/notifications/multi_provider_notifications.py
  camply/notifications/twilio.py
  poetry.lock
  pyproject.toml
Labels: enhancement, BUMP_MINOR

#127 Notification Cleanup
  Dockerfile
  README.md
  camply/notifications/base_notifications.py
  camply/notifications/email_notifications.py
  camply/notifications/multi_provider_notifications.py
  camply/notifications/pushbullet.py
  camply/notifications/pushover.py
  camply/notifications/silent_notifications.py
  camply/notifications/slack.py
  camply/notifications/telegram.py
  camply/notifications/twilio.py
  pyproject.toml
Labels: documentation, BUMP_PATCH, refactoring

#128 Campground Without Recreation Area
  camply/containers/api_responses.py
  camply/providers/recreation_dot_gov/recdotgov_provider.py
  tests/command_line_test.sh
Labels: bug, BUMP_PATCH
