Repository juftin/camply, pull requests merged in 2022-08, with the labels that each got.

#108 Poetry Seed File
  .github/workflows/lint.yml
  camply/_version.py
  pyproject.toml
Labels: enhancement, ci

#111 Bugfix: Release Token
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
Labels: BUMP_MINOR, ci

#112 bugfix/docker_publish
  .github/ISSUE_TEMPLATE/config.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  README.md
  camply/_version.py
  camply/cli.py
  camply/utils/yaml_utils.py
  docs/examples/docker-compose.yaml
  docs/examples/example_search.yaml
  docs/source/index.md
  tests/command_line_test.sh
  tests/yaml/example_campsite_search.yaml
  tests/yaml/example_search.yaml
Labels: ci, BUMP_PATCH

#102 Add slack notification support
  camply/config/__init__.py
  camply/config/file_config.py
  camply/config/notification_config.py
  camply/notifications/__init__.py
  camply/notifications/multi_provider_notifications.py
  camply/notifications/slack.py
  docs/examples/example.camply
Labels: enhancement, BUMP_PATCH

#113 Missed Release
  camply/_version.py
Labels: ci, BUMP_PATCH

#114 BugFix: Contributor Release Permissions
  .github/workflows/release.yaml
Labels: ci, BUMP_PATCH

#115 BugFix: Missing Release
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  camply/notifications/slack.py
Labels: bug, ci, BUMP_PATCH

#116 Latest Cookiecutter Updates
  .github/workflows/docker.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  docs/source/conf.py
Labels: ci, BUMP_PATCH
