Repository juftin/camply, pull requests merged in 2022-12, with the labels that each got.

#163 :bug: semantic-release
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yaml
  .github/labels.yaml
  .github/semantic_release/package-lock.json
  .github/semantic_release/package.json
  .github/semantic_release/set_version.sh
  .github/workflows/docs.yaml
  .github/workflows/labeler.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  .github/workflows/version_checker.yaml
  .gitignore
  .releaserc.yaml
  docs/contributing.md
Labels: bug

#99 ✨ GoingToCamp Provider 🏕
  camply/__init__.py
  camply/cli.py
  camply/containers/__init__.py
  camply/containers/base_container.py
  camply/containers/data_containers.py
  camply/containers/gtc_api_responses.py
  camply/providers/__init__.py
  camply/providers/going_to_camp/__init__.py
  camply/providers/going_to_camp/going_to_camp_provider.py
  camply/search/__init__.py
  camply/search/base_search.py
  camply/search/search_going_to_camp.py
  camply/utils/logging_utils.py
  tests/command_line_test.sh
  tests/search_providers/test_goingtocamp_search.py
Labels: enhancement, camply provider

#155 ✅ Testing Improvements: Cassettes and CLIRunner
  .github/workflows/tests.yaml
  camply/containers/api_responses.py
  camply/containers/data_containers.py
  camply/providers/recreation_dot_gov/recdotgov_provider.py
  camply/search/base_search.py
  poetry.lock
  pyproject.toml
  tests/cassettes/test_pushover_campsite.yaml
  tests/cassettes/test_pushover_message.yaml
  tests/cli/cassettes/test_campground_search_by_campsite_id.yaml
  tests/cli/cassettes/test_campground_search_by_recarea_id.yaml
  tests/cli/cassettes/test_goingtocamp_equipment_types.yaml
  tests/cli/cassettes/test_goingtocamp_search_by_equipment_types.yaml
  tests/cli/cassettes/test_list_recdotgov_campgrounds.yaml
  tests/cli/cassettes/test_search_by_another_yaml.yaml
  tests/cli/cassettes/test_search_by_campground.yaml
  tests/cli/cassettes/test_search_by_campsite_id.yaml
  tests/cli/cassettes/test_search_by_equipment.yaml
  tests/cli/cassettes/test_search_by_recarea.yaml
  tests/cli/cassettes/test_search_by_yaml.yaml
  tests/cli/cassettes/test_search_by_yellowstone_campground.yaml
  tests/cli/cassettes/test_search_error_prone_campground.yaml
  tests/cli/cassettes/test_search_multiple_campsites.yaml
  tests/cli/cassettes/test_search_nights.yaml
  tests/cli/cassettes/test_search_persist_json.yaml
  tests/cli/cassettes/test_search_persist_pickle.yaml
  tests/cli/cassettes/test_search_recreation_areas.yaml
  tests/cli/cassettes/test_search_yellowstone.yaml
  tests/cli/test_campgrounds.py
  tests/cli/test_campsites.py
  tests/cli/test_going_to_camp.py
  tests/cli/test_main.py
  tests/cli/test_recreation_areas.py
  tests/command_line_test.sh
  tests/conftest.py
  tests/pytest.ini
  tests/search_providers/cassettes/test_get_all_campsites.yaml
  tests/search_providers/cassettes/test_get_all_campsites_campground.yaml
  tests/search_providers/cassettes/test_get_all_campsites_recarea.yaml
  tests/search_providers/cassettes/test_get_campsite_specific_campgrounds.yaml
  tests/search_providers/cassettes/test_get_campsite_specific_results.yaml
  tests/search_providers/cassettes/test_get_searchable_campgrounds_campground.yaml
  tests/search_providers/cassettes/test_get_searchable_campgrounds_recarea.yaml
  tests/search_providers/cassettes/test_going_to_camp_get_all_campsites.yaml
  tests/search_providers/cassettes/test_yellowstone_get_all_campsites.yaml
  tests/search_providers/test_goingtocamp_search.py
  tests/search_providers/test_recdotgov_search.py
  tests/search_providers/test_yellowstone_search.py
  tests/test_cli.py
  tests/test_notifications.py
  tox.ini
Labels: bug, testing

#173 🐛 Docker Home Directory
  Dockerfile
Labels: bug

#156 📝 Providers Documentation
  README.md
  docs/_static/goingtocamp_logo.png
  docs/_static/recreation_dot_gov_logo.png
  docs/_static/yellowstone_logo.png
  docs/command_line_usage.md
  docs/extra.css
  docs/index.md
  docs/providers.md
  mkdocs.yml
Labels: documentation, camply provider
